### ISSUE TITLE
Maintain issue.

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/undohist#7]
@tarsius I can help maintain this package. Could you give me the access to this package? Thanks!

**Comment by tarsius** [comment]
We now have two people who are interested in maintaining this package, which is great!

@ideasman42 you should probably start by creating a pull-request, so that @jcs090218 can review it.

Re https://github.com/melpa/melpa/pull/6638.

Oh wait, I just read what you wrote at https://github.com/melpa/melpa/pull/6649. Could you two please look into what the best way forward is.

(By the way, I am quite busy for the next three weeks at least and this isn't a top priority for me.)

**Comment by tarsius** [comment]
Please consider that forking (and immediately releasing) and/or making big changes on the `master` of the existing package aren't the only options. IMO it is better to do whatever you consider to be the best way forward, then using it for a while to see if things work out, and to not release until things have settled.

**Comment by jcs090218** [comment]
Here is my opinion, I can do both! If @ideasman42 thinks his new package [undo-fu-session](https://gitlab.com/ideasman42/emacs-undo-fu-session) is new and different to this package. Then maybe it is better to keep the two packages separated. Then maybe I can maintain this package? 😕

**Comment by ideasman42** [comment]
I'm not sure whats best in this case, if the changes @jcs090218 makes to `undohist` are more or less aligned with what I'm doing, then it doesn't seem so useful to maintain both - unless it's simply to keep things working for anyone who already has `undohist` enabled in their config.

My overall goal is to have an alternative to `undo-tree`, usable for evil / spacemacs - for example.
Which uses emacs undo system (since it's been shown to have [issues](https://www.reddit.com/r/emacs/comments/85t95p/undo_tree_unrecognized_entry_in_undo_list/)).

**Comment by tarsius** [comment]
> My overall goal is to have an alternative to undo-tree

Sounds like your have more ambitious goals. I agree its probably best if you create your own package.

> (since undo-tree has it's own implementation that has issues)

Those issues might be gone: https://www.reddit.com/r/emacs/comments/elg8hw/toby_qubit_cubitt_lost_or_corrupted_undotree/.

**Comment by ideasman42** [comment]
> > (since undo-tree has it's own implementation that has issues)
> 
> Those issues might be gone: https://www.reddit.com/r/emacs/comments/elg8hw/toby_qubit_cubitt_lost_or_corrupted_undotree/.

Yes, hopefully it is, nevertheless, for people who don't use the tree navigation, undo-tree is an overly complex solution. Even if the issue is fixed - it was open for ~6 years, making me think the code-base has a bus-factor of 1 :/

**Comment by jcs090218** [comment]
> I'm not sure whats best in this case, if the changes @jcs090218 makes to undohist are more or less aligned with what I'm doing, then it doesn't seem so useful to maintain both - unless it's simply to keep things working for anyone who already has undohist enabled in their config.

I might just keep the package alive and not further develop this package. At least not what you are targeting now.

> My overall goal is to have an alternative to undo-tree, usable for evil / spacemacs - for example.
Which uses emacs undo system (since undo-tree has it's own implementation that has issues).

According to this.

**Comment by tarsius** [comment]
> I might just keep the package alive and not further develop this package.

Please do that!

**Comment by jcs090218** [comment]
Sounds good! I will close this issue then. :D

@ideasman42 If you have any other concern please comment! :D
